### PR TITLE
[Added] Connection Lost /Logout function

### PR DESCRIPTION
**Pull request by simonrenger**
I ran into some trouble with not being able to login again after I disconnected. That was why I implemented this functions. If there are any questions let me know.

### CODE REVIEW

**Comment by simonrenger** [comment]
The check only failes because of boost/frame....

**Comment by simonrenger** [comment]
Do not commit still contains a bug... fixing it

**Comment by Zandor300** [comment]
Bug fixed again right? So can be merged?

**Comment by simonrenger** [comment]
Not that I am aware of bugs thez should be all fixed

**Pull request merged**
